#! /usr/bin/env python

import roslib

import rospy
import math
import tf
import angles
from geometry_msgs.msg import Twist


if __name__ =='__main__':
    rospy.init_node('charger_tf_listener')

    listener = tf.TransformListener()


    thorvald_vel = rospy.Publisher('/nav_vel', Twist, queue_size=1)

    rate = rospy.Rate(10.0)
    while not rospy.is_shutdown():
        try:
            (trans,rot) = listener.lookupTransform('/base_link','/charger',rospy.Time(0)) #Can also add the fixed frame as a third frame
            print(rot)
        except(tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            continue

        #tf.transformations.quaternion_from_euler(0, 0, theta),
        # ang_error = math.atan2(trans[1],trans[0])
        # if abs(ang_error) >= 0.3:
        #     angular = 4*ang_error
        # else:
        #     angular = 0
        # print(ang_error)
        angular = -angles.normalize_angle(math.acos(rot[3]))
        print(angular)
        linear = 0.5*math.sqrt(trans[0]**2 + trans[1]**2)
        cmd = Twist()
        if abs(linear) > 0.4:
            cmd.linear.x = 0.4*linear/abs(linear)
        cmd.angular.z = angular
        thorvald_vel.publish(cmd)

        rate.sleep()
