#! /usr/bin/env python

import rospy
import actionlib
import rospy
import numpy as np
import math
import tf
import angles

import actionlib
import actionlib_msgs
import move_base_msgs.msg
#import move_base_msgs.msg

from geometry_msgs.msg import Twist, Pose, PoseStamped
from nav_msgs.msg import Odometry
import matplotlib.pyplot as plt

class align_action(object):
    #messages for publishing feedback and result
    _feedback = move_base_msgs.msg.MoveBaseFeedback()
    _result = move_base_msgs.msg.MoveBaseResult()
    def __init__(self, name):
        self._action_name = name
        self._as = actionlib.SimpleActionServer(self._action_name, move_base_msgs.msg.MoveBaseAction, execute_cb=self.execute_cb, auto_start=False)
        self._as.start()

    def execute_cb(self, goal):
        # helper variables
        rate = rospy.Rate(1)
        success = True

        #Current position (Thorvald_state)
        x = 3.1415
        y = 6.2830
        # self._feedback.base_position.pose.position.x = x
        # self._feedback.base_position.pose.position.y = y
        rospy.loginfo("%s: executing... current position: (%f, %f)" %(self._action_name,x,y))

        #Check that preempt has not been requested
        if self._as.is_preempt_requested():
            rospy.loginfo("%s: preempted..." %self._action_name)
            self._as.set_preempted()
            success = False
            #break
        rate.sleep()

        if success:
            #self._result.success = True
            rospy.loginfo("%s: succeeded!"%self._action_name)
            self._as.set_succeeded(self._result)
if __name__ == "__main__":
    rospy.init_node("align_action")
    server = align_action(rospy.get_name())
    rospy.spin()
