#!/usr/bin/env python
import roslib
import rospy
import math
import tf
from geometry_msgs.msg import Twist

if __name__ == '__main__':
    rospy.init_node('charger_listener')

    listener = tf.TransformListener()
    thorvald_command = rospy.Publisher('nav_vel', Twist,queue_size=1)

    rate = rospy.Rate(10.0)
    while not rospy.is_shutdown():
        try:
            (trans,rot) = listener.lookupTransform('charger', 'base_link', rospy.Time(0))
        except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            continue

        angular = 4 * math.atan2(trans[1], trans[0])
        linear = 0.5 * math.sqrt(trans[0] ** 2 + trans[1] ** 2)
        cmd = Twist()
        cmd.linear.x = linear
        cmd.angular.z = angular
        thorvald_command.publish(cmd)

        rate.sleep()
